language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.4.2
  - DJANGO=1.3.4
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q . --use-mirrors
script:
  - python runtests.py
notifications:
  email:
    recipients:
      - philipe.rp@gmail.com
    on_success: change
    on_failure: change
branches:
  only:
    - master
    - dev
